# Generated by Django 5.0.14 on 2026-05-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('subject', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Engineering', 'Engineering'), ('Business & Economics', 'Business & Economics'), ('Humanities & Social Sciences', 'Humanities & Social Sciences'), ('Other', 'Other')], default='Other', max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_size', models.FloatField(help_text='File size in MB')),
                ('file_type', models.CharField(help_text='File extension (e.g., pdf, docx)', max_length=10)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
